version: "3.9"
services:
  envault:
    build: .
    ports:
      - 8000:80
    env_file: .env
    depends_on:
      - db
      - mailhog

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: envault


  mailhog:
    image: mailhog/mailhog
    ports:
    - "1025:1025"
    - "8025:8025"